name: Release job
description: build affected packages and publish them to npm
inputs:
  gh_token:
    description: 'Github token'
    required: true
  gh_name:
    description: 'Github name'
    required: true
  gh_email:
    description: 'Github email'
    required: true
runs:
  using: "composite"
  steps:
    - uses: './.github/actions/setup-environment'
    - name: Install deps
      shell: bash
      run: npm i
    - name: git config
      shell: bash
      run: |
        git config user.name "${{ inputs.gh_name }}"
        git config user.email "${{ inputs.gh_email }}"
    - name: Release version
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        # Disable legacy peer deps to ensure proper dependency resolution
        # See: https://github.com/nrwl/nx/issues/22066#issuecomment-2576366862
        # See: https://github.com/nrwl/nx/blob/5ea2e47acfa9d175546daa922ce40905533f1074/packages/nx/src/utils/package-manager.ts#L207-L213
        npm_config_legacy_peer_deps: false
      run: npx nx release version
    - name: Release publish
      shell: bash
      run: npx nx release publish
  
