name: Cypress runner cache
description: Retrieve and cache the cypress runner
runs:
  using: "composite"
  steps:
    # cache cypress runner
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cypress-cache
      with:
        path: ~/.cache/Cypress
        key: cypress-runner-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
