name: PR title lint
permissions:
  contents: read
on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened]

jobs:
  pr-title-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - name: Install
        shell: bash
        run: npm ci
      - name: Validate PR title with commitlint
        shell: bash
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint --verbose
