name: Upload tests to Ibutsu
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests-upload:
    runs-on: ubuntu-latest
      #    container:
      #image: quay.io/cloudservices/iqe-artifact-uploader-s3
      #credentials:
      #  username: ${{ secrets.QUAY_INSIGHTS_QE_LOGIN }}
      #  password: ${{ secrets.QUAY_INSIGHTS_QE_PASSWORD }}
      #env:
      #  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      #  AWS_REGION: ${{ secrets.AWS_REGION }}
      #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: docker login -u ${{ secrets.QUAY_INSIGHTS_QE_LOGIN }} -p ${{secrets.QUAY_INSIGHTS_QE_PASSWORD}} quay.io
      - run: docker pull quay.io/cloudservices/iqe-artifact-uploader-s3
      - run: docker run --mount "type=bind,source=./dummyreport,destination=/results" . -e AWS_BUCKET="${{ secrets.AWS_BUCKET }}" -e AWS_REGION="${{ secrets.AWS_REGION }}" -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" quay.io/cloudservices/iqe-artifact-uploader-s3:latest
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # force install of mocha reporter
      - run: npm install mocha-ibutsu-reporter
      - run: npm ci
      - run: npm run test:ci
      - name: Merge tests results
        working-directory: ./packages/components
        run: merge-results --config cypress.json
      - name: Upload results to Ibutsu
        working-directory: ./packages/components
        run: upload-artifact-s3
